### ISSUE TITLE
checklist for people upgrading to genome-grist v0.9.0

### ISSUE THREAD

**Issue by ctb** [dib-lab/genome-grist#220]
I plan to cut a new release pretty soon, but we've made a few changes that will catch people by surprise if they upgrade - so writing this down to include instructions in the release notes.

also this can serve as a reminder to myself to update the mkdocs site upon release 🙄 

## changes since 0.8.x series -

- [x] **if** we remove the abundtrim step per https://github.com/dib-lab/genome-grist/pull/199, then the details on how to provide your own metagenomes will change. We should suggest people (a) turn off SRA download and (b) rename their abundtrim files.
- [x] in #209 and #219, we changed a bunch of column names in the mapping summary output, but then also helpfully documented them! so point at the new documentation! Users will want to regenerate their `mapping/*.summary.csv` and `leftover/*.summary.csv` files.
- [x] in https://github.com/dib-lab/genome-grist/pull/213 we switched to gzipping the output files from sourmash. So if you want to avoid rerunning prefetch and gather, you'll need to gzip them. We should provide instructions!

people to inform of release: @jeanzzhao, @hehouts, @jessicalumian

**Comment by ctb** [comment]
## Brief guide to upgrading existing analyses from v0.8.4

### Preventing genome-grist from rerunning sourmash

In #213 the CSV output files from `sourmash prefetch` and `sourmash gather` change to be compressed .csv.gz files, while the content stays the same. To prevent genome-grist from rerunning these searches, you should compress the files. We suggest going into the output directory and running:
```
gzip gather/*.gather.csv gather/*.prefetch.csv
```
No rerunning should be needed.

### Regenerating mapping summary files

In #209 and #209 the column names in the mapping summary output change significantly. To regenerate these files with the new code, you can simply remove them and rerun. We suggest going into the outputs directory and running:
```
rm mapping/*.summary.csv leftover/*.summary.csv
```
and then running target `summarize_mapping` to regenerate them.

### Using private metagenomes

In #199, the read filenames that are used for the rest of genome-grist's analyses have changed from `abundtrim/{sample}.abundtrim.fq.gz` to `abundtrim/{trim}.trim.fq.gz`. If you have emplaced your own metagenome data sets, you will need to rename them.

We suggest manually renaming each file as above, and additionally adding:
```
prevent_sra_download: true
```
to your config file.

### Regenerating all read-based results

In #199, genome-grist changes the way read data is processed so that only basic adapter trimming and quality score filtering is done, and khmer-based variable coverage k-mer trimming is _not_ applied. This should have only small impact on k-mer or mapping based outputs, but it _will_ change them. Please see the discussion in https://github.com/dib-lab/genome-grist/issues/197 for more details on why this change was made.

We do not recommend that users generate new results because of this change, but to do so, you will want to remove the intermediate sourmash outputs:
```
rm -fr sigs gather
```
and then rerun `summarize`.

**Comment by ctb** [comment]
released! advice in #225.
